### PR TITLE
Update prow config to kfctl_istio_dex config

### PR DESCRIPTION
**Pull request by krishnadurai**
/assign @yanniszark @gabrielwen 

kubeflow/kubeflow#4501

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/96)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@yanniszark could you please take a look at this?

This clears up the pathway for kubeflow/manifests#620.

**Comment by yanniszark** [comment]
Thanks @krishnadurai!

/lgtm
/approve

**Comment by yanniszark** [comment]
cc @krishnadurai maybe this needs a rebase?
This doesn't seem related: 

```
kubeflow-kfctl-presubmit-kfctl-go-iap-96-1801bd1-8480-1c0b-deploy_pytorchjob-pytorch-job:

Subprocess failed; level=error msg="validating registry URL: validating GitHub registry URL: \"https://github.com/kubeflow/kubeflow/tree/master/kubeflow/registry.yaml\" actual 404; expected 200"
--
```

**Comment by krishnadurai** [comment]
@yanniszark did a rebase right now. Let's see if it passes.

**Pull request merged**
