### PR TITLE
Pytorch pytest

### PR DESCRIPTION
**Pull request by gabrielwen**
Related: #97 

Rewrite pytorch job E2E test in pytest.

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/137)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen FYI I'll review this PR when its no longer in the draft state.

**Comment by gabrielwen** [comment]
> @gabrielwen FYI I'll review this PR when its no longer in the draft state.

yea sounds good it's still WIP.

**Comment by gabrielwen** [comment]
@jlewi ok it's ready for review now.

**Comment by jlewi** [comment]
@gabrielwen looks good. Can you

* Update the PR with a helpful description
* Update the PR description with the issues this fixes
* Rebase and squash commits

As soon as that's done I'll LGTM

**Comment by gabrielwen** [comment]
@jlewi updated.

**Comment by jlewi** [comment]
@gabrielwen looks like you didn't squash the commits but we can live with out it.

Thanks for doing this.

/lgtm
/approve

**Comment by gabrielwen** [comment]
> @gabrielwen looks like you didn't squash the commits but we can live with out it.
> 
> Thanks for doing this.
> 
> /lgtm
> /approve

I removed some commits that is for debugging.

**Pull request merged**
