### PR TITLE
Add Jeffwan as approver

### PR DESCRIPTION
**Pull request by Jeffwan**
Here's the contributions.
https://github.com/kubeflow/kfctl/pulls/Jeffwan

We (AWS) still uses kfctl to install Kubeflow in 1.1 version, probably 1.2 and future versions as well. 
I would like to put more efforts to help improve experiences for kfctl users. 

I am trying to apply for approver to help community features and requests.

### CODE REVIEW

**Comment by PatrickXYS** [comment]
@Jeffwan has continuously contributed to kubeflow/kfctl!

**Comment by jlewi** [comment]
/hold

@animeshsingh @crobby @Jeffwan @vpavlin @yanniszark You are the primary maintainers/users of kfctl so you should really be the ones to approve this.

**Comment by jlewi** [comment]
I should probably be removed from the root OWNERs file.

**Comment by animeshsingh** [comment]
@Jeffwan is awesome, and has contributed greatly.

/lgtm

**Comment by Jeffwan** [comment]
rebase conflicts.

**Comment by jlewi** [comment]
I can no longer approve this change; so removing myself as a reviewer.

**Comment by yanniszark** [comment]
@animeshsingh @crobby @Jeffwan @vpavlin if everything is in order, just remove the hold :smile:

**Pull request merged**
