### PR TITLE
Return error when the cache path is a sub directory of local manifests repo

### LINKED ISSUE #260: error - Filename too long
Hello

I'm trying to follow the instructions for installing kubeflow on Openshift.

Step 2 says:

> sed -i 's#uri: .*#uri: '$PWD'#' ./kfdef/kfctl_openshift.yaml
> kfctl build --file=kfdef/kfctl_openshift.yaml

This last command significantly increases the disk space used - the `manifest` folder jumps in size to over 7 gigs! 

And it errors with the following:

```
kfctl build --file=kfdef/kfctl_openshift.yaml
Error: failed to build kfApp from URI kfdef/kfctl_openshift.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: lstat /media/anton/win/docs/git/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/docs/dex-auth/examples/authorization/Kubernetes/cluster_read_all_cluster_role_binding.yaml: file name too long
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl build -V --file=${CONFIG}
  -h, --help          help for build
  -V, --verbose       verbose output default is false

failed to build kfApp from URI kfdef/kfctl_openshift.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error: lstat /media/anton/win/docs/git/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/kfdef/.cache/manifests/docs/dex-auth/examples/authorization/Kubernetes/cluster_read_all_cluster_role_binding.yaml: file name too long
```
## Version

kfctl v1.0-0-g94c35cf

### PR DESCRIPTION
**Pull request by adrian555**
Closes #260 

There are two symptoms reported in the above issue. One is the error `Filename too long`. The other one is the disk space under the local manifests repo will keep growing (7GB+) if keep trying the command.

The error message does not provide a good explanation of what the problem really is yet some file disk copy does not get cleaned up.

This PR aims to return a better error message and exit if the cache directory for the manifests is actually a sub directory of the manifests repo itself.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/272)

### CODE REVIEW

**Comment by gabrielwen** [comment]
thanks!  could you also add a test case for the change?

**Comment by adrian555** [comment]
> thanks! could you also add a test case for the change?

@gabrielwen I have added a test case. Please review. Thanks!

**Pull request merged**
