### PR TITLE
Add tests to KfConfig v1beta1

### PR DESCRIPTION
**Pull request by amalts**
Addresses kubeflow/kubeflow#4162

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/107)

### CODE REVIEW

**Comment by amalts** [comment]
@googlebot I signed it!

**Comment by jlewi** [comment]
/assign @gabrielwen 

@gabrielwen please review this

@amalts Thank you so much for the contribution!

**Comment by gabrielwen** [comment]
thanks for the contribution!  overall looks good, only having some minor comments.

**Comment by amalts** [comment]
> > _[Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/107)_ status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @amalts and @gabrielwen)
> 
> _[pkg/apis/apps/kfconfig/types_test.go, line 67 at r1](https://reviewable.io/reviews/kubeflow/kfctl/107#-LuYwWMAEw5SNyFx9Nyt:-LuYwWMAEw5SNyFx9Nyu:b-5tbu7s) ([raw file](https://github.com/kubeflow/kfctl/blob/b4228344a9601b8591045983c237b4fbc71670e7/pkg/apis/apps/kfconfig/types_test.go#L67)):_
> 
> > ```go
> > 			},
> > 		},
> > 		// The following test cases pull from GitHub. The may be worth commenting
> > ```
> 
> do we still need these commented codes?
> 

This commented code only makes sense for local testing. I ensured that it works as expected. But if it doesn't add much value, we can remove it.

Addressed remaining comments @gabrielwen.

**Comment by gabrielwen** [comment]
/lgtm
/approve

thanks for the contribution!

**Pull request merged**
