### PR TITLE
update operator name from kfctl to kubeflow in OLM

### PR DESCRIPTION
**Pull request by adrian555**
Currently the kubeflow operator is shown as `kfctl` in the OLM (operator lifecycle manager). This PR changes the name to `kubeflow` to reflect better what it has deployed. Same change is also made on the `operator-framework/community-operators` repo https://github.com/operator-framework/community-operators/pull/1309.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/270)

### CODE REVIEW

**Comment by animeshsingh** [comment]
thanks @adrian555 - can you add the equivalent link for operatorhub PR here?

**Comment by adrian555** [comment]
@animeshsingh link added to the description above. Thanks.

**Comment by animeshsingh** [comment]
thanks @adrian555 - can you update the PR there with the same title - the title there is misleading

**Comment by adrian555** [comment]
@animeshsingh https://github.com/operator-framework/community-operators/pull/1309 merged.

**Comment by animeshsingh** [comment]
thanks

/lgtm
/approve

**Pull request merged**
