### PR TITLE
fixing name of secretGenerator key in kustomize file generation

### LINKED ISSUE #210: kfctl kustomize secretGenerator is broken
Hi y'all. I was deploying master of the `kubeflow/manifests` and the metadata server wasn't coming up. The pod was stuck in a pending state trying to mount a secret that was not on the system. In the [metadata/overlays/db/kustomization.yaml](https://github.com/kubeflow/manifests/blob/master/metadata/overlays/db/kustomization.yaml#L12-L14) file that secret _should_ be generated by kustomize.

I ran `kustomize build ... | kubectl apply -f -` and that worked... After pawing through the source code a bit, I learned that kfctl does some merging of it's own beyond rending the overlays with kustomize. The `README.md` in the manifests repo also talks about this.

I added a test case for it, and to be expected it failed. After looking through the file I finally found the error. The key value is `secretGenerator` not `secretGeneratorMap`. After changing that the test passed! Leaving this issue here as a warning to anyone else who tries to deploy the master manifests until my PR is merged.

*You can make the changes I made and compile the binary yourself if you don't want to wait.

### PR DESCRIPTION
**Pull request by WillBeebe**
Fixes #210

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/212)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @Tomcli 
/assign @zhenghuiwang 

@TomCLI It looks like you just fixed a bug in kfctl #187 could you please take a look at this PR?

**Comment by zhenghuiwang** [comment]
/lgtm

I think the bug was fixed in #187 but this PR adds the tests. Thanks @WillBeebe and l will let @Tomcli comment on it.

**Comment by jlewi** [comment]
Drive by approve
/lgtm
/approve

**Pull request merged**
