### PR TITLE
sync with kubeflow v0.6.0-rc.0-207-gad0893ee

### PR DESCRIPTION
**Pull request by kkasravi**
snapshot taken of kubeflow master at Sat Oct 19 11:56:41 PDT 2019

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/51)

### CODE REVIEW

**Comment by kkasravi** [comment]
@jlewi this is broken due to kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py not finding the py_func 'kubeflow.kubeflow.ci.kfctl_e2e_workflow.create_workflow' even though the prow_config includes 
```
python_paths:
  - kubeflow/kubeflow/py
```

**Comment by jlewi** [comment]
@kkasravi I think that's because run_e2e_workflow.py only checks out the repo that triggered the test (kubeflow/kfctl) and kubeflow/testing.

There's two possible solutions

1. We can modify run_e2e_workflow.py to add the ability to checkout additional repos listed in prow_config.yaml
   * E.g. add a statement here https://github.com/kubeflow/testing/blob/c5e803aec396b4e0425943eccd102b32ef043a96/py/kubeflow/testing/run_e2e_workflow.py#L157
   * to clone additional repos listed in prow_config.yaml

1. Alternatively we could copy over the python code from kubeflow/kubeflow to kubeflow/kfctl

We will probably need to do both at some point.

**Comment by kkasravi** [comment]
thanks @jlewi - had a short conversation with @richardsliu who might be able to try this (thanks @richardsliu ) - this afternoon. I'm snowed on some intel work - may have some free cycles tomorrow or on the weekend.

**Comment by richardsliu** [comment]
@kkasravi @jlewi Yes I'll pick this up this afternoon.

**Comment by richardsliu** [comment]
@kkasravi @jlewi Can we copy the directories from `kubeflow/py/kubeflow/kubeflow/ci` to `testing/py/kubeflow`? Then wouldn't all the other repos be able to use it?

**Comment by kkasravi** [comment]
replaced by @richardsliu 's PR

**Pull request closed without merging**
