### PR TITLE
Revert "Enable istio injection in Kubeflow namespace"

### PR DESCRIPTION
**Pull request by richardsliu**
Reverts kubeflow/kfctl#131

See https://github.com/kubeflow/kfctl/issues/296

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @richardsliu 

@Bobgy @zhenghuiwang WDYT? Do you think reverting #131 is the right course of action?

**Comment by zhenghuiwang** [comment]
> @Bobgy @zhenghuiwang WDYT? Do you think reverting #131 is the right course of action?

LGTM.

**Comment by Bobgy** [comment]
I think postsubmit was run, because the PR was created from a branch not in forked repo.

kfp's postsubmit is configured to only run on master branch, you may do something similar

**Pull request merged**
