### PR TITLE
sync with kubeflow/kubeflow v0.6.0-rc.0-105-g2f15d8db

### PR DESCRIPTION
**Pull request by kkasravi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/37)

### CODE REVIEW

**Comment by hougangliu** [comment]
/lgtm
@kkasravi  thanks

**Comment by gabrielwen** [comment]
Makefile seems to be wrong and that made the test failed.  it's copying deepcopy generated files with path `v3/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go`, but you should put `$GOPATH` as prefix.

**Pull request closed without merging**
