### PR TITLE
Kfdef v1

### PR DESCRIPTION
**Pull request by gabrielwen**
Related: #73

Adding `KfDef` v1 - mostly copied from v1beta1.

Please let me know if you think we need to update the definitions!

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/117)

### CODE REVIEW

**Comment by kunmingg** [comment]
Shall we take care this: https://github.com/kubeflow/kfctl/blob/master/pkg/apis/apps/kfconfig/types.go#L53

**Comment by gabrielwen** [comment]
> Shall we take care this: https://github.com/kubeflow/kfctl/blob/master/pkg/apis/apps/kfconfig/types.go#L53

that's `KfConfig`.  but yea we should do that as internal code improvement.

**Comment by jlewi** [comment]
> Please let me know if you think we need to update the definitions!

What does update definitions mean? 

Are there any changes to the KFDef spec relative to v1beta1.

/lgtm
/approve
/hold

Assuming there are no API changes relative to v1beta1 you can go ahead and remove the hold.

**Pull request merged**
