### PR TITLE
fix typo to avoid panic in operator controller

### PR DESCRIPTION
**Pull request by adrian555**
Toward #243 

The current kfctl does seems to expect a repo name `manifests` as the code shows https://github.com/kubeflow/kfctl/blob/9e8a07225b04d96eccf37dd0316e02a9a1e72f67/pkg/kfapp/kustomize/kustomize.go#L397 using the const https://github.com/kubeflow/kfctl/blob/c5c55f6d1b79e285f28fa433d6e4e2e739cefb63/pkg/apis/apps/group.go#L52.

This PR only fixed the specific code error in the operator side where the error was not caught due to a typo.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/259)

### CODE REVIEW

**Comment by Tomcli** [comment]
@adrian555 I believe this just fix the error panic right? is it fixing the #243 with the repo name?

**Comment by adrian555** [comment]
@Tomcli this only fixed the error panic in operator code as the title and description say. We can leave #243 open if we want to use it for supporting any repo name.

**Comment by Tomcli** [comment]
ok thanks @adrian555 
/lgtm

**Pull request merged**
