### PR TITLE
Automated cherry pick of #145: fix file:/ with local tarball

### PR DESCRIPTION
**Pull request by gabrielwen**
Related: #124 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/149)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen any idea why the tests are failing?

**Comment by gabrielwen** [comment]
> @gabrielwen any idea why the tests are failing?

@jlewi that is because in v0.7 branch `KfConfig` is in `/pkg/apis/apps/kfconfig`, but in master branch and this PR it's in `/pkg/kfconfig`.  I need to close this PR and branch from v0.7 branch to patch the change.

**Pull request closed without merging**
