### PR TITLE
Automated cherry pick of #90: Make KFCTL E2E tests self contained in repo

### PR DESCRIPTION
**Pull request by gabrielwen**
We deleted kfctl testing codes in kubeflow repo but in v0.7 kfctl repo E2E tests depend on them.

Notebook test was disabled because the fix was in #142

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/150)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen instead of commenting out the tfjob and notebooks test, can we mark them as expected to fail?

Can you call this out in the PR description please? Do we have issues tracking fixing and enabling the tests that we can link to?

**Comment by gabrielwen** [comment]
> @gabrielwen instead of commenting out the tfjob and notebooks test, can we mark them as expected to fail?
> 
> Can you call this out in the PR description please? Do we have issues tracking fixing and enabling the tests that we can link to?

we don't have tracking issues for them.  both tests are fixed in master branch, do you think we need to cherrypick those PRs to v0.7 branch as well?  or should we leave 0.7 branch only testing on build and deploy as it is right now?

**Comment by gabrielwen** [comment]
@jlewi the test is fixed.

**Pull request merged**
