### PR TITLE
Automated cherry pick of #187: fix SecretGenerator bug Cherry pick of #187 on v1.0-branch. #187: fix SecretGenerator bug

### PR DESCRIPTION
**Pull request by richardsliu**
Fixes https://github.com/kubeflow/manifests/issues/799

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/204)

### CODE REVIEW

**Comment by richardsliu** [comment]
@Tomcli Can you reply on this PR and confirm that you consent? It's a cherry pick for PR #187

**Comment by Tomcli** [comment]
@googlebot I consent.

**Pull request closed without merging**
