### PR TITLE
Cherry-pick of #439 and #440 to v1.2-branch

### PR DESCRIPTION
**Pull request by pvaneck**
This cherry-picks #439 and #440  in to v1.2-branch.

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/lgtm
/approve

Thanks @pvaneck !

**Comment by PatrickXYS** [comment]
```
           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps \"metadata-ui\" not found","reason":"NotFound","details":{
"name":"metadata-ui","group":"apps","kind":"deployments"},"code":404}
```

This is because this PR is not yet cherry-picked https://github.com/kubeflow/kfctl/pull/440

**Comment by pvaneck** [comment]
@PatrickXYS  Want me to cherry-pick that in this PR?

**Comment by PatrickXYS** [comment]
@pvaneck  I sent a PR as of now, https://github.com/kubeflow/kfctl/pull/442, can you lgtm?

**Comment by pvaneck** [comment]
@PatrickXYS I cherry-picked #440 here as well.

**Comment by PatrickXYS** [comment]
/lgtm
/approve
/hold
Hold until test succeed

**Comment by PatrickXYS** [comment]
@pvaneck Feel free to unhold to merge the PR

**Pull request merged**
