### PR TITLE
adds kfctl_k8s_istio config as a pre-submit test

### PR DESCRIPTION
**Pull request by swiftdiaries**
Adds the default config - `kfctl_k8s_istio.yaml` part of the pre-submit tests.
/cc @kkasravi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/11)

### CODE REVIEW

**Comment by jlewi** [comment]
@swiftdiaries is this ready for review?

**Comment by swiftdiaries** [comment]
I need to pull in changes. Let me do that now

**Pull request closed without merging**
