### PR TITLE
Kustomize cleanup error handling

### PR DESCRIPTION
**Pull request by discordianfish**
My main goal here was just surfacing the error here: https://github.com/kubeflow/kfctl/pull/264/files#diff-85e9677c1c2a51f1c1d287363401b6a7R438

But since I've been at it, I've also tried to improve the error formatting/logging in general:

- Uppercase log entries
- Lowercase errors
- Always add err to returned err
- Replace " Error " prefix by ": " to be consistend and more go
  idiomatic

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/264)

### CODE REVIEW

**Comment by discordianfish** [comment]
Can't really figure out what failed.. Maybe it's just temporarily

/retest

**Comment by discordianfish** [comment]
Let's hope this fixes it. If not, some input would be welcome. Dunno what is going on with the code gen.

/assign @kunmingg

**Comment by discordianfish** [comment]
This was the issue before I've added the GOROOT workaround:
```
go: error loading module requirements
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x68f4e6]
goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc0000b16d0, 0xc0000ce340, 0x30, 0x1, 0xc0000d7c88)
        /go/src/k8s.io/gengo/parser/parse.go:233 +0xb6
k8s.io/gengo/args.(*GeneratorArgs).NewBuilder(0xc0000b8aa0, 0xc0000aec40, 0x10, 0x28)
        /go/src/k8s.io/gengo/args/args.go:143 +0x22e
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000b8aa0, 0xc0000d7e48, 0x758567, 0x6, 0x784420, 0x0, 0x0)
        /go/src/k8s.io/gengo/args/args.go:192 +0x4d
main.main()
        /go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:77 +0x45d
Makefile:81: recipe for target 'pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go' failed
make: *** [pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go] Error 2
```

**Comment by discordianfish** [comment]
@kunmingg Looks like the unit tests pass now but the 'upgrade' and 'go-iap' workflows fail. I can't find any error there though, not in the build log. Can you tell me what is going wrong here?

**Comment by discordianfish** [comment]
@kunmingg I've just rebased this and fixed the merge conflicts. Can we get this through before this happens again?

**Comment by discordianfish** [comment]
The only issues I see in the build log are with failing workflows. But the only step that failed in the workflows is the exit handler and the wait for kubeflow steps.. unclear why. Let see if restarting the test makes a difference.

/retest

**Comment by kunmingg** [comment]
error from delete:
`couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 400 with message: Cluster name doesn't match: KfDef(dummy) v.s. current-context(gke_kube
flow-ci-deployment_us-central1-a_kfctl-358f)`

Can you try rebase master head?

**Comment by kunmingg** [comment]
Sorry tests were flaky recently.

**Comment by discordianfish** [comment]
Rebased, let see..

**Comment by discordianfish** [comment]
@kunmingg Same error.. can you help me understand why it's failing? Neither the buildlog nor the logs of any of the workflow steps reveal anything. It looks to me like an issue with the tests themselves, unrelated to this PR. Can you confirm that? If so, can we still merge this as-is? I can't really justify spending more time on this right now..

**Comment by discordianfish** [comment]
@kunmingg I've rebased this again

**Comment by jlewi** [comment]
On the most recent test run.
katib failed the is ready test.

The ugprade test failed on the delete test.

The periodic tests are showing some failures
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-kfctl

The tests will need to be fixed in order to unblock this and other PRs.

@discordianfish I understand your frustration and totally get it if you can't spend more time on this. We do however need to get the tests fixed first.

**Comment by jlewi** [comment]
btw instructions for debugging failed tests are here:
https://github.com/kubeflow/testing#debugging-failed-tests

In my reply above I followed the links to the Argo Workflows UI for the workflows and then looked at the logs for the failed steps.

**Comment by jlewi** [comment]
#57 is tracking some larger improvements to testing for KFCTl to reduce the impact of flaky E2E tests on presubmits.

**Comment by discordianfish** [comment]
So I saw that the end2end tests failed, but I didn't (and still don't) see why, so I can't help fixing them. From looking at the the dashboard, it seems like almost all tests fail. But looking that the PRs, it seems they eventually succeeded. Still confused tbh..
But I guess I just try to re-run the test, hoping it will succeed eventually..

/test kubeflow-kfctl-postsubmit

**Comment by discordianfish** [comment]
Ok looks like the workaround of setting GOROOT is needed after all. Still don't understand why other PRs don't run into these same issues. I'll keep trying to rerun the tests a few more times.

**Comment by Jeffwan** [comment]
Testing infra is kind of flaky now..

**Comment by discordianfish** [comment]
Ok, I've rebased this again and looks like the tests have been fixed. Can we get this merged now @kunmingg?

**Comment by discordianfish** [comment]
@yanniszark Can you maybe approve/review?

**Pull request merged**
