### PR TITLE
Sync kfctl with kubeflow/kubeflow at dfd8b2b

### PR DESCRIPTION
**Pull request by richardsliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/72)

### CODE REVIEW

**Comment by kkasravi** [comment]
@richardsliu were the tests moved over as well?

**Comment by richardsliu** [comment]
@kkasravi You mean the e2e tests? I copied them manually (they failed one of the previous runs).

**Comment by kkasravi** [comment]
> @kkasravi You mean the e2e tests? I copied them manually (they failed one of the previous runs).

ok. We may want to add that logic into the hack/ script. Also i was add a note in the description of what the kubeflow/kubeflow kfctl version is and the time. Prior sync PRs have this info.

/lgtm
/approve

**Pull request merged**
