### PR TITLE
Fix deps in kfapp and kfdef

### PR DESCRIPTION
**Pull request by gabrielwen**
Related: #73 #68 
This is part of removing deps on `kfdef` in `/kfapps` folders.  This PR makes plugins both `/gcp` and `/aws` self-contained so that their dependencies on `SecretRef` and `RepoRef` are removed.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/78)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen Could you please update the PR description with a bit more explanation on what this change is doing, why & how?

**Comment by gabrielwen** [comment]
> @gabrielwen Could you please update the PR description with a bit more explanation on what this change is doing, why & how?

updated.

**Comment by gabrielwen** [comment]
since you are removing `UseIstio` field, do you mind also remove it here?
https://github.com/kubeflow/kfctl/blob/08a2e3736b2ca25f1f7a327090ecc48e014aa90b/pkg/apis/apps/kfconfig/types.go#L62

**Comment by gabrielwen** [comment]
@jlewi can we merge this?  I've had another PR working on #68

**Pull request merged**
