### PR TITLE
Cherry Pick PR #440

### PR DESCRIPTION
**Pull request by PatrickXYS**
Cherry Pick #440 to avoid test failure

/cc @pvaneck

### CODE REVIEW

**Comment by PatrickXYS** [comment]
lol I changed the commit author @pvaneck Can you lgtm again?

**Comment by pvaneck** [comment]
I'm curious if this will complain about autoscaler-hpa not being found now, since the other cherry-pick complained about metadata-ui. Perhaps better if both cherry-picks are in one PR.

**Comment by PatrickXYS** [comment]
@pvaneck  Good point, let's do it in one single PR, can you help to cherry-pick this PR in your PR as well.

And then I'll close my PR

**Comment by PatrickXYS** [comment]
/close

Close in favor of https://github.com/kubeflow/kfctl/pull/441

**Pull request closed without merging**
