### PR TITLE
[WIP] endpoint test failure

### PR DESCRIPTION
**Pull request by gabrielwen**
WIP

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/227)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen I added WIP to the title just so its more evident in the PR dashboard that its still in WIP. just remove it when its ready for me to review.

**Comment by gabrielwen** [comment]
Python version problem seems to be fixed.  Need to figure out why endpoint creation is not as expected now.

**Pull request closed without merging**
