### PR TITLE
Fix csv version

### PR DESCRIPTION
**Pull request by evan-hataishi**
Fixes the file name as described in one of the tasks in https://github.com/kubeflow/kfctl/issues/422.

CSV generated with operator-sdk 0.16
Tested on OCP 4.5 with this [kfdef](https://github.com/moficodes/manifests/blob/master/kfdef/kfctl_openaihub_openshift_tekton.yaml)

### CODE REVIEW

**Comment by Tomcli** [comment]
@evan-hataishi so no code changes for 1.1 release except the filename?

**Comment by evan-hataishi** [comment]
> @evan-hataishi so no code changes for 1.1 release except the filename?

@Tomcli Nope, just a fix for the filename.

**Comment by Tomcli** [comment]
@evan-hataishi how about for 1.2? I think we will have the official 1.2 release this week.

**Comment by evan-hataishi** [comment]
@Tomcli It looks like we're keeping track of all the versions, so I'll work on that next and put it in a new PR

**Comment by Tomcli** [comment]
I see, it looks like the olm Kubeflow 1.1 release was using the old name. This probably fix that bug.
/lgtm

**Comment by Jeffwan** [comment]
Seems this is OLM only. 

/approve

**Pull request merged**
