### PR TITLE
update coordinator/converters/gcp API for kfctlserver

### PR DESCRIPTION
**Pull request by kunmingg**
This PR is Part of https://github.com/kubeflow/kubeflow/pull/4399: only include changes on kfctl side.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/76)

### CODE REVIEW

**Comment by kunmingg** [comment]
@jlewi 
Will update unit tests once got lgtm on API changes

**Comment by gabrielwen** [comment]
since you are removing `UseIstio` field, do you mind also remove it here?
https://github.com/kubeflow/kfctl/blob/08a2e3736b2ca25f1f7a327090ecc48e014aa90b/pkg/apis/apps/kfconfig/types.go#L62

**Comment by kunmingg** [comment]
@jlewi 
On router side I try to not use disk to avoid race condition among threads, and replace go-getter with http.get. So if we use go-getter on coordinator then kfctl and kfctl-server will diverge in supporting different types of URIs.

**Comment by kunmingg** [comment]
updated

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
on my end looks good thanks!
@gabrielwen any additional comments?

**Pull request merged**
