### PR TITLE
Make KFCTL E2E tests self contained in repo

### PR DESCRIPTION
**Pull request by gabrielwen**
Related to kubeflow/kfctl#91
Related to kubeflow/kfctl#7

- Make KFCTL E2E tests self-contained within repo.
- Reorder python testing codes to be within package path: `kubeflow/kfctl/...`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/90)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen Do you need to

* Add the new flag to conftest?
* Modify the workflow?

**Comment by jlewi** [comment]
Rename 'py/kfctl to py/kubeflow/kfct' So that all imports are `import kubeflow.kfctl`

**Comment by gabrielwen** [comment]
test has passed, so I think code moving is complete.  let me put them into the appropriate place.

**Comment by gabrielwen** [comment]
/retest

manually cleaned up quotas.

**Comment by gabrielwen** [comment]
@jlewi this PR is ready.

**Pull request merged**
