### PR TITLE
Add test data to KfConfig tests

### PR DESCRIPTION
**Pull request by amalts**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/114)

### CODE REVIEW

**Comment by amalts** [comment]
This will fix TestKfConfig_GetPluginSpec test case

**Comment by amalts** [comment]
@gabrielwen There was a test failure for TestKfConfig_GetPluginSpec due to missing test data file. This will fix it.

**Comment by gabrielwen** [comment]
could you move the test to `/pkg/kfconfig`?  thanks.

**Comment by amalts** [comment]
@gabrielwen Done.

**Comment by amalts** [comment]
@googlebot I consent

**Comment by gabrielwen** [comment]
/lgtm
/approve

thanks :)

**Comment by amalts** [comment]
@gabrielwen Looks like there is an error with gcp service account in e2e. Does it require a manual merge?

**Pull request merged**
