### PR TITLE
Fix KfConfig unittest

### PR DESCRIPTION
**Pull request by gabrielwen**
- It was in the wrong directory.
- It needs testdata.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/122)

### CODE REVIEW

**Comment by lluunn** [comment]
presubmit was broken? Or the test is not run by presubmit?

**Comment by gabrielwen** [comment]
> presubmit was broken? Or the test is not run by presubmit?

somehow it's not checking failing tests.  I've called it out in build-cop channel.

**Comment by amalts** [comment]
@gabrielwen I noticed this after the test PR got merged. Raised https://github.com/kubeflow/kfctl/pull/114 for the fix.

**Comment by gabrielwen** [comment]
@amalts could you move the tests to `/pkg/kfconfig`?  that is the new directory and the one you put it in right now will be removed soon.

**Comment by gabrielwen** [comment]
moving to #114 
/close

**Pull request closed without merging**
