### PR TITLE
pretty print log messages IAM policy

### PR DESCRIPTION
**Pull request by Anamika28**
Existing pretty print function is utilised in places, where logs need to be printed in json format.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@Anamika28 Thanks for the contribution. Could you sign CLA?  seems `kfutils.PrettyPrint` just return one result, let's have one line for it

```
log.Infof("ManagedCluster set defaulting to %v", kfutils.PrettyPrint(*awsPluginSpec.ManagedCluster))
```

**Comment by Jeffwan** [comment]
@Anamika28 Do you want to rebase change and sign CLA?

**Comment by Jeffwan** [comment]
Can not reach out the original author. I replicate a PR #362 to resolve this issue. 

/close

**Comment by Anamika28** [comment]
Hi Kubeflow/kfctl,

Sorry for the delayed reply, I want to sign the CLA, can you please help?

Thanks and Regards
Anamika | Developer
+91 8130810825

**Pull request closed without merging**
