### PR TITLE
Update version output to 1.2.0

### PR DESCRIPTION
**Pull request by evan-hataishi**
Update version output to 1.2.0 as requested in sub task in issue https://github.com/kubeflow/kfctl/issues/422

### CODE REVIEW

**Comment by evan-hataishi** [comment]
Looks like Weiqiang is still being automatically added as a reviewer to these PRs @Tomcli

**Review by adrian555 — APPROVED** [review]

**Comment by adrian555** [comment]
Once this PR is merged and cherry-picked to `v1.2-branch`, please remember to open a PR on `v1.2-branch` and update the `deploy/operator.yaml` file with the pre-built operator v1.2.0 image. And if required, also need to generate the new csv in the `deploy/olm-catalog` directory. Thanks.

**Comment by Jeffwan** [comment]
/lgtm

Please help cherry-pick to 1.2 and I can help approve that

**Pull request merged**
