### PR TITLE
Enable istio injection in Kubeflow namespace

### PR DESCRIPTION
**Pull request by Bobgy**
/cc @jlewi 
Can you help me review?

Resolves  https://github.com/kubeflow/kubeflow/issues/3866
This PR is imitating https://github.com/kubeflow/kfctl/pull/123, which is similar

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfctl/131)

### CODE REVIEW

**Comment by jlewi** [comment]
@Bobgy This change looks good but before we can merge this change, I think we need to update kubeflow/manifests and disable ISTIO side car injection for most services to preserve the current behavior.

**Comment by Bobgy** [comment]
@jlewi I didn't manage to get enough time to do this today.
Just asking if there's any documentation to build kfctl by myself? I want to build a specific kfctl just for demo.

**Comment by jlewi** [comment]
@Bobgy you should just be able to run make
https://github.com/kubeflow/kfctl/blob/10c827128a9b7ffaae4794f37127946c8cba9b51/Makefile#L122

**Comment by Bobgy** [comment]
@jlewi Thanks! I will build a binary by myself first.

/hold for kubeflow manifest change

**Comment by Bobgy** [comment]
FYI, I built the binary directly, it's working well. Thanks!

**Comment by Bobgy** [comment]
@jlewi We tried using https://github.com/kubeflow/kfctl/blob/10c827128a9b7ffaae4794f37127946c8cba9b51/Makefile#L126, but the built tar package doesn't work for Mac OS. When we execute `kfctl`, it errors
```
cannot execute binary file
```
it seems it is still built for linux. How do we build one for Mac?

/cc @gaoning777

**Comment by jlewi** [comment]
@Bobgy see kubeflow/kfctl/#161

**Comment by gaoning777** [comment]
Awesome. I guess it should be working from https://github.com/kubeflow/kfctl/pull/162, then.

**Comment by Bobgy** [comment]
The last blocker: https://github.com/kubeflow/manifests/pull/716

**Comment by jlewi** [comment]
Looks like a bunch of tests are failing.

**Comment by Bobgy** [comment]
I read the error message saying there is an error running kustomize apply for 0.7-branch, because webhook doesn't respond.

That's expected because with the flag turned on webhook is inaccessible by default.

Only when using master branch, would the deploy work.

**Comment by jlewi** [comment]
It looks like two workflows failed.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kfctl/131/kubeflow-kfctl-presubmit/1222548130831011840/

The first failure is the upgrade test. The build deploy step failed. Here are the logs
[kubeflow-kfctl-presubmit-kfctl-upgrade-131-60282bb-1840-be2e-2151024252.log.txt](https://github.com/kubeflow/kfctl/files/4136749/kubeflow-kfctl-presubmit-kfctl-upgrade-131-60282bb-1840-be2e-2151024252.log.txt)

The error is 

```
2020-01-29T16:14:22.161951781Z  main            util.py                     72 INFO     failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout371770818": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-a2f5e105802182d81b09"?
```

The test is trying to apply the 0.7.0 config.

```
2020-01-29T15:55:05.423739423Z  wait            time="2020-01-29T15:55:05Z" level=info msg="Executor (version: v2.2.1, build_date: 2018-10-11T16:27:29Z) initialized with template:\nactiveDeadlineSeconds: 3000\narchiveLocation: {}\ncontainer:\n  command:\n  - pytest\n  - kfctl_go_test.py\n  - -s\n  - --app_name=kfctl-2eae\n  - --config_path=https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml\n 
```

This looks like it might be related to the GKE 1.14 bug with workload identity. This should be fixed in the 0.7.1 manifests but I'm guessing not the 0.7.0 configs.

@richardsliu what is the best way to fix the upgrade tests?

@Bobgy Could you please file a P0 bug about the upgrade test failures and assign to @richardsliu 

Looking at our periodic test grid. 
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-kfctl-postsubmit&group-by-hierarchy-pattern=%5B%5Cw-%5D%2B

It looks like the build_deploy step is passing. So you might need to rebase to pick up changes to fix the test.

**Comment by Bobgy** [comment]
Thanks for the investigation, I will continue efforts on this after vacation.

**Comment by Bobgy** [comment]
Merged current master, waiting to see test results

**Comment by Bobgy** [comment]
@jlewi Is there any way I can debug the test cluster? I cannot find any error message in the presubmit. Looks like the tfjob smoke test just timed out.

I guess tfjob couldn't work with istio injection by default. Shall we patch it to also add the disable istio injection annotation? What other operators there are? pytorch?

I worry the list will go on forever. Shall we go with enable the label but change cluster default to not inject?

**Comment by Bobgy** [comment]
Looking at https://github.com/kubeflow/kubeflow/issues/3935, it confirms that tfjobs cannot run in istio auto injection enabled namespaces. tfjob must explicitly disable sidecar injection.

**Comment by Bobgy** [comment]
Exact error message
```
Timeout waiting for job to finish: Job:
{
  "status": {
    "conditions": [
      {
        "status": "True", 
        "lastUpdateTime": "2020-03-03T03:13:21Z", 
        "lastTransitionTime": "2020-03-03T03:13:21Z", 
        "reason": "TFJobCreated", 
        "message": "TFJob smoke-tfjob-kfctl-gcp-iap is created.", 
        "type": "Created"
      }, 
      {
        "status": "True", 
        "lastUpdateTime": "2020-03-03T03:14:05Z", 
        "lastTransitionTime": "2020-03-03T03:14:05Z", 
        "reason": "TFJobRunning", 
        "message": "TFJob smoke-tfjob-kfctl-gcp-iap is running.", 
        "type": "Running"
      }
    ], 
    "replicaStatuses": {
      "PS": {
        "active": 2
      }, 
      "Chief": {
        "active": 1
      }, 
      "Worker": {
        "active": 4
      }
    }, 
    "startTime": "2020-03-03T03:13:21Z"
  }, 
  "kind": "TFJob", 
  "spec": {
    "tfReplicaSpecs": {
      "PS": {
        "restartPolicy": "Never", 
        "template": {
          "spec": {
            "containers": [
              {
                "image": "gcr.io/kubeflow-examples/tf_smoke:v20180814-c6e55b4d", 
                "name": "tensorflow"
              }
            ]
          }
        }, 
        "replicas": 2
      }, 
      "Chief": {
        "restartPolicy": "Never", 
        "template": {
          "spec": {
            "containers": [
              {
                "image": "gcr.io/kubeflow-examples/tf_smoke:v20180814-c6e55b4d", 
                "name": "tensorflow"
              }
            ]
          }
        }, 
        "replicas": 1
      }, 
      "Worker": {
        "restartPolicy": "Never", 
        "template": {
          "spec": {
            "containers": [
              {
                "image": "gcr.io/kubeflow-examples/tf_smoke:v20180814-c6e55b4d", 
                "name": "tensorflow"
              }
            ]
          }
        }, 
        "replicas": 4
      }
    }
  }, 
  "apiVersion": "kubeflow.org/v1", 
  "metadata": {
    "name": "smoke-tfjob-kfctl-gcp-iap", 
    "generation": 1, 
    "labels": {
      "app.kubernetes.io/deploy-manager": "ksonnet", 
      "ksonnet.io/component": "simple_tfjob_v1"
    }, 
    "namespace": "kubeflow", 
    "resourceVersion": "8297", 
    "creationTimestamp": "2020-03-03T03:13:21Z", 
    "annotations": {
      "ksonnet.io/managed": "{\"pristine\":\"H4sIAAAAAAAA/8yPQUszMRCG79/PmPNu2y3tR8lV8OBBihU9iJTZdHaNm2RCMq5KyX+XdKnYf9DbwJs37/McAYN5opgMe1AwfLTUWf6cceznYwMVDMYfQMHj7R23UIEjwQMKgjqCxZZsKteQ2HuSmeG5ZhfYkxdQkIwLlvbSvXO7HxvIFXh0VBLHA9WnoB46LbbudagNBpiepICa/vCUagqky5h0DxSs0bgLpE/zN2+GunLEKUigmgoiJcEoW7ZGf4OCexopQgVCLlgUKoXzn5q9oPEUE6iXIxiHfZnvdSxOZ4qavrAYpbl0+5OCGpeLZrPYNKta/6f1ul0d4FdSyCeOE/5rzrmC7e6ScnmVlM8cB4qXpKsrJM05//sBAAD//wEAAP//VbSiq8ACAAA=\"}"
    }, 
    "selfLink": "/apis/kubeflow.org/v1/namespaces/kubeflow/tfjobs/smoke-tfjob-kfctl-gcp-iap", 
    "uid": "f007f35a-5cfc-11ea-a52b-42010a8001f2"
  }
}
```

**Comment by Bobgy** [comment]
/retest
try again

**Comment by Bobgy** [comment]
Hi @gabrielwen, it seems you contributed a lot of test infra here.
Can you help me with troubleshooting this PR?

I'm trying to add `"annotations": { "sidecar.istio.io/inject": "false" }` to all test workloads to verify if that was the cause of test timeout.
Can you help me review if my changes look good? Did I miss anything else? I worry I should also add this label for tfjobs, but I cannot find it.

**Comment by jlewi** [comment]
@Bobgy we have some debugging instructions here:
https://github.com/kubeflow/testing#debugging-failed-tests

**Comment by Bobgy** [comment]
Thanks, let me take a look

**Comment by jlewi** [comment]
@Bobgy do you know what the test failures are? Is it still TFJob? Did you try patching the test to not run with ISTIO side car injection?

**Comment by Bobgy** [comment]
@jlewi, thanks for following up!

> @Bobgy do you know what the test failures are? Is it still TFJob?

Yes, tfjob-smoke-test is still timing out without any explicit error messages.
The actual error should be very clear if I can look at tfjob pod status or log, but even after I requested permission in https://github.com/kubeflow/internal-acls/pull/221, I am still not able to view kubeflow-ci and kubeflow-ci-deployment projects in GCP. If that's resolved, I can take a look.

> Did you try patching the test to not run with ISTIO side car injection?

I tried patching the test in https://github.com/kubeflow/kfctl/pull/131/commits/b3ddd39f204f733999cb714aec80eff54127c922, but now I understand I wasn't patching the right yaml. I should be patching TFJob, but I haven't found it yet.

**Comment by Bobgy** [comment]
OK, now I understand this line: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kfctl/131/kubeflow-kfctl-presubmit/1239771165149368320/#1:build-log.txt%3A749 is actually calling test in https://github.com/kubeflow/tf-operator/blob/master/py/kubeflow/tf_operator/simple_tfjob_tests.py

but I still don't know which version is it pulling, is it tf operator's master? Should I send a PR in tf operator repo to add that annotation?

**Comment by jlewi** [comment]
The google groups need to be sync'd manually (there's an open issue to fix that). So you may or may not have been added to the group and that could explain why you still don't have access (kubeflow/internal-acls#22).

If you need to fix the test you will need to submit a PR to the repo that fixes the test.

I believe its pulling the test from tf-operator at HEAD
https://github.com/kubeflow/kfctl/blob/5c47b2d5912cea1f31f699aab886c8f25f1c9e4f/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py#L71

/cc @johnugeorge @richardsliu

**Comment by Bobgy** [comment]
Thanks for the help! I will try to make a PR for tf-operator test

**Comment by jlewi** [comment]
@Bobgy I just checked and it looks like the groups hadn't been sync'd since you submitted your PR to join ci-viewer team. I sync'd them and you should now be a member.

**Comment by Bobgy** [comment]
@jlewi Thanks! I verified I can see `kubeflow-ci-deployment` project logs now

**Comment by jlewi** [comment]
Fantastic work! Thanks for the persistence.

/lgtm
/approve

**Comment by Bobgy** [comment]
@jlewi Thanks for your help!

/unhold

**Pull request merged**
